name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: 1.16
      id: go
    - name: Check out code
      uses: actions/checkout@v3
    - name: Runs tests
      run: make
